/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.fade.demo.gradledemo;

/**
 * java-libraries-sample
 * @author fade
 * */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
