/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.fade.demo.gradledemo.app;

import org.fade.demo.gradledemo.list.LinkedList;

import static org.fade.demo.gradledemo.utilities.StringUtils.join;
import static org.fade.demo.gradledemo.utilities.StringUtils.split;
import static org.fade.demo.gradledemo.app.MessageUtils.getMessage;

import org.apache.commons.text.WordUtils;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        String result = join(tokens);
        System.out.println(WordUtils.capitalize(result));
    }
}
